# Generated by Django 3.0.8 on 2020-07-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('second_last_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('origin', models.CharField(max_length=255)),
                ('born_date', models.DateField()),
                ('born_place', models.CharField(max_length=255)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_specie', models.CharField(max_length=255)),
                ('habitat', models.CharField(max_length=255)),
                ('endangered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.IntegerField()),
                ('max_visitors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Single_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Single')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Tour')),
            ],
        ),
        migrations.AddField(
            model_name='single',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Specie'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_enter', models.CharField(blank=True, max_length=100, null=True)),
                ('time_exit', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Person')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Rol')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Shelter')),
            ],
        ),
    ]
